### ISSUE TITLE
Everytime I install with Nuget, it cannot find the namespace Google

### ISSUE THREAD

**Issue by thomasmoors** [glacasa/TwoStepsAuthenticator#10]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Google' could not be found (are you missing a using directive or an assembly reference?)	2F.DNX Core 5.0	C:\Users\Thomas\git\2F\src\2F\Helpers\KeyHelper.cs	5	Active

VS 2015, new ASP.NET Web API project

**Comment by glacasa** [comment]
Just remove c'est Google namespace, this is not a Google product.

The project is in the TwoStepsAuthenticator namespace, you can see the correct usage in the readme file
