### ISSUE TITLE
how to generate a temporary code that expires in 15 minutes?

### ISSUE THREAD

**Issue by whatsdis** [glacasa/TwoStepsAuthenticator#12]
I'm building an Multi factor authentication and would like teh server to send a six digit code to the client which he must enter within 15 minutes. should I use a the counterauthenticator for this using the same secret key for timeauthenticator?

going forward I am using timeauthenticator but for MFA I'd like to generate a code they send back to me to confirm they aren't a spammer upon sign up.

**Comment by glacasa** [comment]
If you want a code that automatically expires, you should use a time authenticator - but it will be available less than 5 minutes, not 15.

This library is made to be compatible with Google/Microsoft authenticator apps, if you want other usages, you should do it by yourself (just generate a random code, and save it for 15 minutes in session state)
