### ISSUE TITLE
Signed assembly

### ISSUE THREAD

**Issue by MiguelAlho** [glacasa/TwoStepsAuthenticator#14]
Are you considering signing the distributed assembly? This is usefull (and necessary) if consuming the library in a signed library or app.

**Comment by glacasa** [comment]
I have never done this for public distribution, I'm not sure what is needed exactly.

**Comment by MiguelAlho** [comment]
It's rather quite simple - I can send in a PR with the changes if you'd like. You only need a .snk file, and some build properties added. I have a project that requires signed assemblys (since it itself is signed). For now I'm using a custom package with signed version, but would rather have the original signed, if possible.

Some projects have been opting in to using a different package (something like TwoStepsAuthenticator-Signed), Projects built against a signed .dll get "locked" to that version of the .dll, so .dll substitution can be somewhat clumsy; a different package for the signed assembly can aid resolving that issue, giving users an option.

**Comment by glacasa** [comment]
Ok, I think I can do that.
I have to keep the snk private (not on the public Github rep), right ?

**Comment by MiguelAlho** [comment]
Idealy, yeah, out of the repo , since it is a key and has private key info associated to it.

**Comment by AngelVHS** [comment]
I am having the same issue so I am looking forward for this to happen.

**Comment by glacasa** [comment]
The last NuGet package is signed
https://www.nuget.org/packages/TwoStepsAuthenticator/1.3.0
