### ISSUE TITLE
PCL compatible

### ISSUE THREAD

**Issue by ruisilva450** [glacasa/TwoStepsAuthenticator#15]
Hi,
I want to use this library on an Xamarin forms app.
There are plans to make a PCL?

**Comment by glacasa** [comment]
I have thought about a .NET standard version (it should work with Xamarin) - but didn't take the time to do it.
I will try to look at this soon.

**Comment by MiguelAlho** [comment]
would https://github.com/glacasa/TwoStepsAuthenticator/pull/17 help in this?

**Comment by glacasa** [comment]
Thanks to this last pull request, TwoStepsAuthenticator 1.3 is compatible .net standard 1.6, and sould work with Xamarin
https://www.nuget.org/packages/TwoStepsAuthenticator/1.3.0
