### ISSUE TITLE
Define time verification range as parameter

### ISSUE THREAD

**Issue by eduardo-pereira** [glacasa/TwoStepsAuthenticator#18]
We've been experiencing several issues related with clock skews. It would be nice to define the verification range during initialization.

At the moment, the checkcode method goes from -2 to 1.
The change would make it to go from -value to value, being the default, for instance, 2.

Looking forward to hear from you.

**Comment by glacasa** [comment]
The TimeAuthenticator ctor now has a verificationRange param, defaulting to 2.

The CheckCode method checks from `- verificationRange` to `verificationRange - 1`

**Comment by eduardo-pereira** [comment]
Thanks for the quick change. It works like a charm and will keep us out of trouble.
