### ISSUE TITLE
nuget package

### ISSUE THREAD

**Issue by 304NotModified** [glacasa/TwoStepsAuthenticator#7]
Is there a nuget package for this nice lib?

**Comment by glacasa** [comment]
No, but it may change ;) I will look at that

**Comment by 304NotModified** [comment]
Do you have appveyor running as build server?

**Comment by glacasa** [comment]
I use TFS as build server, it's also able to upload package to Nuget.

It's now available here : https://www.nuget.org/packages/TwoStepsAuthenticator/

**Comment by 304NotModified** [comment]
Thanks!
